name: Update Timestamp
on:
  schedule:
    - cron: "0 12 * * *"  # 每天 UTC 时间 12:00 运行（北京时间 20:00）
  workflow_dispatch:      # 支持手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Update timestamp
        run: |
          pip install pytz  # 安装时区库
          python update_timestamp.py

      - name: Commit changes
        if: ${{ github.repository_owner == github.actor }}  # 避免 Fork 仓库冲突
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: auto-update timestamp"
          git push